# Header
menu:
  主页: /
  归档: /archives
  关于: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

copyright: |-
  <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a></br>
  All website licensed under <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0</a></br>
  <a style="display:inline-flex;align-items:center;margin-top:5px;" href="https://beian.mps.gov.cn/#/query/webSearch" ><img style="width: 16px;margin-right:4px" src="https://beian.mps.gov.cn/img/logo01.dd7ff50e.png" alt=""><span>京ICP备2024078215号</span></a></br>

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
- archive

# Widget behavior
archive_type: 'monthly'
show_count: true
recent_posts_limits: 5

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
fb_admins:
fb_app_id:

# valine comment system. https://valine.js.org
valine:
  enable: true # if you want use valine,please set this value is true
  appId: Hw3KvMbHtgDZgkcYFa3ilGy2-gzGzoHsz # leancloud application app id
  appKey: QafIch9rnzZMId31sXeeODN0  # leancloud application app key
  notify: true # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
  verify: true # valine verify code (true/false)
  pageSize: 100 # comment list page size
  avatar: mm # gravatar style https://valine.js.org/#/avatar
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info
